
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftADDSUBleftMULDIVrightNEGnonassocPOWADD DIV ENDL LPAREN MUL NUM POW RPAREN SUBline : expr ENDLline : error ENDLexpr : numberexprpow : numberpowexpr : LPAREN expr RPARENexprpow : LPAREN exprpow RPARENexpr : SUB LPAREN expr RPAREN %prec NEGexprpow : SUB LPAREN exprpow RPAREN %prec NEGexpr : expr ADD exprexprpow : exprpow ADD exprpowexpr : expr SUB exprexprpow : exprpow SUB exprpowexpr : expr MUL exprexprpow : exprpow MUL exprpowexpr : expr POW exprpowexpr : expr DIV exprexprpow : exprpow DIV exprpownumber : NUMnumberpow : NUMnumber : SUB number %prec NEGnumberpow : SUB numberpow %prec NEG'
    
_lr_action_items = {'error':([0,],[3,]),'LPAREN':([0,5,6,9,10,11,12,13,17,24,25,30,31,32,33,36,],[5,5,17,5,5,5,24,5,5,24,36,24,24,24,24,24,]),'SUB':([0,2,4,5,6,7,9,10,11,12,13,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,],[6,10,-3,6,16,-18,6,6,6,25,6,10,16,6,-20,-9,-11,-13,-15,-4,25,35,-19,-16,-5,10,25,25,25,25,31,35,25,-21,-7,-10,-12,-14,-17,-6,31,-8,]),'NUM':([0,5,6,9,10,11,12,13,16,17,24,25,30,31,32,33,35,36,],[7,7,7,7,7,7,26,7,7,7,26,26,26,26,26,26,26,26,]),'$end':([1,8,14,],[0,-1,-2,]),'ENDL':([2,3,4,7,18,19,20,21,22,23,26,27,28,37,38,39,40,41,42,43,45,],[8,14,-3,-18,-20,-9,-11,-13,-15,-4,-19,-16,-5,-21,-7,-10,-12,-14,-17,-6,-8,]),'ADD':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[9,-3,-18,9,-20,-9,-11,-13,-15,-4,-19,-16,-5,9,30,-21,-7,-10,-12,-14,-17,-6,30,-8,]),'MUL':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[11,-3,-18,11,-20,11,11,-13,-15,-4,-19,-16,-5,11,32,-21,-7,32,32,-14,-17,-6,32,-8,]),'POW':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,37,38,39,40,41,42,43,45,],[12,-3,-18,12,-20,12,12,12,-15,-4,-19,12,-5,12,-21,-7,-10,-12,-14,-17,-6,-8,]),'DIV':([2,4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[13,-3,-18,13,-20,13,13,-13,-15,-4,-19,-16,-5,13,33,-21,-7,33,33,-14,-17,-6,33,-8,]),'RPAREN':([4,7,15,18,19,20,21,22,23,26,27,28,29,34,37,38,39,40,41,42,43,44,45,],[-3,-18,28,-20,-9,-11,-13,-15,-4,-19,-16,-5,38,43,-21,-7,-10,-12,-14,-17,-6,45,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'line':([0,],[1,]),'expr':([0,5,9,10,11,13,17,],[2,15,19,20,21,27,29,]),'number':([0,5,6,9,10,11,13,16,17,],[4,4,18,4,4,4,4,18,4,]),'exprpow':([12,24,30,31,32,33,36,],[22,34,39,40,41,42,44,]),'numberpow':([12,24,25,30,31,32,33,35,36,],[23,23,37,23,23,23,23,37,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> line","S'",1,None,None,None),
  ('line -> expr ENDL','line',2,'p_line_expr','yaccer.py',31),
  ('line -> error ENDL','line',2,'p_line_error','yaccer.py',41),
  ('expr -> number','expr',1,'p_expr_number','yaccer.py',56),
  ('exprpow -> numberpow','exprpow',1,'p_exprpow_number','yaccer.py',65),
  ('expr -> LPAREN expr RPAREN','expr',3,'p_expr_paren','yaccer.py',73),
  ('exprpow -> LPAREN exprpow RPAREN','exprpow',3,'p_exprpow_paren','yaccer.py',77),
  ('expr -> SUB LPAREN expr RPAREN','expr',4,'p_expr_neg','yaccer.py',81),
  ('exprpow -> SUB LPAREN exprpow RPAREN','exprpow',4,'p_exprpow_neg','yaccer.py',87),
  ('expr -> expr ADD expr','expr',3,'p_expr_add','yaccer.py',93),
  ('exprpow -> exprpow ADD exprpow','exprpow',3,'p_exprpow_add','yaccer.py',99),
  ('expr -> expr SUB expr','expr',3,'p_expr_sub','yaccer.py',105),
  ('exprpow -> exprpow SUB exprpow','exprpow',3,'p_exprpow_sub','yaccer.py',111),
  ('expr -> expr MUL expr','expr',3,'p_expr_mul','yaccer.py',118),
  ('exprpow -> exprpow MUL exprpow','exprpow',3,'p_exprpow_mul','yaccer.py',124),
  ('expr -> expr POW exprpow','expr',3,'p_expr_pow','yaccer.py',130),
  ('expr -> expr DIV expr','expr',3,'p_expr_div','yaccer.py',136),
  ('exprpow -> exprpow DIV exprpow','exprpow',3,'p_exprpow_div','yaccer.py',152),
  ('number -> NUM','number',1,'p_number_pos','yaccer.py',169),
  ('numberpow -> NUM','numberpow',1,'p_numberpow_pos','yaccer.py',174),
  ('number -> SUB number','number',2,'p_number_neg','yaccer.py',180),
  ('numberpow -> SUB numberpow','numberpow',2,'p_numberpow_neg','yaccer.py',184),
]
